# Generated by Django 3.0.7 on 2020-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branch_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='organisarion',
            name='org_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='id',
            field=models.AutoField(auto_created=True, default=55, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisarion',
            name='id',
            field=models.AutoField(auto_created=True, default=22, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
