# Generated by Django 3.0.7 on 2020-06-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_auto_20200616_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='branch.Organisarion'),
        ),
    ]
